### ISSUE TITLE
forked repo in RGSoC organisation

### ISSUE THREAD

**Issue by alicetragedy** [Aumrr/AlphaRubyTeam#1]
Hi @Aumrr, it seems that this repo was accidentally forked into our RGSoC organisation (see: https://github.com/rails-girls-summer-of-code/AlphaRubyTeam). since you already have a (private) repo to communicate with your team on our organisation, I am going to delete the fork that was added to our organisation – just wanted to let you know first.

**Comment by Aumrr** [comment]
Hi @alicetragedy  yes it was forked while testing.Thank you for informing.

**Comment by alicetragedy** [comment]
@Aumrr no problem just thought I should let you know. 
The repo has been deleted, so I'm going to close this issue now!
